exports.ROLE_CODE = {
  DRIVER: 1001,
  CUSTOMER: 1000,
  ADMIN: 9999,
  INCOMPLETE_PROFILE: 2204
};
exports.ROLE_NAME = {
  DRIVER: 'DRIVER',
  CUSTOMER: 'CUSTOMER',
  ADMIN: 'ADMIN',
  INCOMPLETE_PROFILE: 'INCOMPLETE_PROFILE'
};
exports.CATEGORY_CODE = {
  SMALL_VEHICLE: 'SMALL_VEHICLE',
  LARGE_VEHICLE: 'LARGE_VEHICLE'
};
